// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GiveAID.V2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MakeDonationUserIdNullable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Make user_id nullable to support anonymous donations
            // FK constraint remains but now allows NULL values for anonymous donations
            migrationBuilder.AlterColumn<int>(
                name: "user_id",
                table: "donations",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: false);

            // Update FK constraint to allow null without IsRequired
            migrationBuilder.DropForeignKey(
                name: "FK_donations_users_UserId",
                table: "donations");

            migrationBuilder.AddForeignKey(
                name: "FK_donations_users_UserId",
                table: "donations",
                column: "user_id",
                principalTable: "users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert: Make user_id NOT NULL again
            migrationBuilder.DropForeignKey(
                name: "FK_donations_users_UserId",
                table: "donations");

            migrationBuilder.AlterColumn<int>(
                name: "user_id",
                table: "donations",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_donations_users_UserId",
                table: "donations",
                column: "user_id",
                principalTable: "users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
